import axios from "axios";

const bookingApi = axios.create({
  baseURL:
    "https://booking-api-ventixe-e5hydeevg6htf7br.swedencentral-01.azurewebsites.net/api",
  timeout: 60000,
  headers: {
    Accept: "application/json",
    "Content-Type": "application/json",
  },
});

//Generated by ChatGPT-04-mini-high - Adds JWT token to requests if available
bookingApi.interceptors.request.use(
  (config) => {
    const token = sessionStorage.getItem("jwtToken");
    if (token) {
      config.headers.Authorization = `Bearer ${token}`;
    }
    return config;
  },
  (error) => {
    return Promise.reject(error);
  }
);

export default bookingApi;
