import React from 'react';
import { NavLink, useLocation } from 'react-router-dom';

const BreadcrumbNav = () => {
    const location = useLocation();
    const { pathname } = location;

    const pathnames = pathname.split('/').filter((x) => x);

    // Generated by Claude 3.5 Sonnet - Determine the className based on number of path segments
    const containerClassName = pathnames.length <= 1 ? 'basePage' : 'underPage';
    return (
        <div className={`breadcrumb ${containerClassName}`}>
            {pathnames.map((name, index) => {
                const routeTo = `/${pathnames.slice(0, index + 1).join('/')}`;
                return (
                    <React.Fragment key={routeTo}>
                        <NavLink to={routeTo}
                            className={({ isActive }) => `pageLink ${isActive ? 'active' : ''}`}>
                            {name.split('-').map(word => word.charAt(0).toUpperCase() + word.slice(1)).join(' ')}
                        </NavLink>
                    </React.Fragment>
                );
            })}
        </div>
    );
};

export default BreadcrumbNav;
